# Generated by Django 3.1.3 on 2020-12-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0002_doctor_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='catagory',
            new_name='category',
        ),
    ]
