# Generated by Django 3.1.3 on 2020-12-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_auto_20201223_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neorology', 'Neorology'), ('Nephrology', 'Nephrology'), ('Medicine', 'Medicine'), ('Dermatology', 'Dermatology'), ('Neorosurgery', 'Neorosurgery'), ('Cardiacsurgery', 'Cardiacsurgery')], max_length=200, null=True),
        ),
    ]
