# Generated by Django 3.1.3 on 2020-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0004_auto_20201224_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neorology', 'Neorology'), ('Nephrology', 'Nephrology'), ('Medicine', 'Medicine'), ('Dermatology', 'Dermatology'), ('Neorosurgery', 'Neorosurgery'), ('Cardiacsurgery', 'Cardiacsurgery'), ('ENT', 'ENT')], max_length=200, null=True),
        ),
    ]
